---
title: "iNEXTパッケージを用いた解析"
author: "加藤千尋"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---

```{r}
# 関数の読み込み
library(tidyverse)
library(iNEXT)

# データの読み込み
COI <- read_csv("data_raw/COICustom157bp/23111007_1COICustom157bp/4_相同性が高い生物種リスト(BLAST結果10位まで).csv")
trnL <- read_csv("data_raw/trnL-c_trnL-h-150bp/23111007_2trnL-c_trnL-h-150bp/4_相同性が高い生物種リスト(BLAST結果10位まで).csv")
```

```{r}
#| echo: false
#| layout-ncol: 2
# trnL、リード削除なし
trnL_inext <-
  trnL %>%
  select(ASV_ID:Tsudanum23_trnL) %>%
  column_to_rownames("ASV_ID") %>%
  iNEXT(q = 0, datatype = "abundance")
ggiNEXT(trnL_inext) +
  labs(title = "trnL")

# trnL、リード削除100以下
trnL_inext_100 <-
  trnL %>%
  select(ASV_ID:Tsudanum23_trnL) %>%
  column_to_rownames("ASV_ID") %>%
  filter(Shinmats23_trnL > 100 | Chiba23_trnL > 100 | Tsudanum23_trnL > 100) %>% 
  iNEXT(q = 0, datatype = "abundance")
ggiNEXT(trnL_inext_100) +
  labs(title = "trnL(リード数100以下のASVを削除)")
```

```{r}
#| echo: false
#| layout-ncol: 3

# COI、リード削除なし
COI_iNEXT <-
  COI %>%
  select(ASV_ID:Tsudanum23_ZBJ) %>%
  column_to_rownames("ASV_ID") %>%
  iNEXT(q = 0, datatype = "abundance")
ggiNEXT(COI_iNEXT) +
  labs(title = "COI")

# COI、リード削除10以下
COI_iNEXT_10 <-
  COI %>%
  select(ASV_ID:Tsudanum23_ZBJ) %>%
  column_to_rownames("ASV_ID") %>%
  filter(Shinmats23_ZBJ > 10 | Chiba23_ZBJ > 10 | Tsudanum23_ZBJ > 10) %>% 
  iNEXT(q = 0, datatype = "abundance")
ggiNEXT(COI_iNEXT_10) +
  labs(title = "COI(リード数10以下のASVを削除)")

# COI、リード削除100以下
COI_iNEXT_100 <-
  COI %>%
  select(ASV_ID:Tsudanum23_ZBJ) %>%
  column_to_rownames("ASV_ID") %>%
  filter(Shinmats23_ZBJ > 100 | Chiba23_ZBJ > 100 | Tsudanum23_ZBJ > 100) %>% 
  iNEXT(q = 0, datatype = "abundance")
ggiNEXT(COI_iNEXT_100) +
  labs(title = "COI(リード数100以下のASVを削除)")
```


### 各ASVと種の対応表_trnL

<https://docs.google.com/spreadsheets/d/1EByvbiL1dI2_A18lY3g3OqXs6lC_TgcriWWzxicqhlE/edit?usp=sharing>
