---
title: "参考文献メモ"
author: "加藤千尋"
format: html
editor: visual
---

**No.01**\
**Title**: Evaluation and optimization of microbial DNA extraction from fecal samples of wild Antarctic bird species.\
**Author**: Eriksson\
**Year**: 2017\
**Link**: <https://doi.org/10.1080/20008686.2017.1386536>\
**Contents**: 鳥類の糞中に含まれる尿酸がDNA抽出を阻害することについて\
**Usage**: 2.1.4 サンプリングした排泄物の処理

------------------------------------------------------------------------

**No.02**\
**Title**: 動物食性動物を対象とした食性解析手法\
**Author**: 小村健人\
**Year**: 2020\
**Link**: <https://doi.org/10.18960/seitai.70.1_91>\
**Contents**: 食性解析の手法\
**Usage**:

------------------------------------------------------------------------

**No.03**\
**Title**: 植物食性動物を対象とした食性解析手法\
**Author**: 安藤温子\
**Year**: 2020\
**Link**: <https://doi.org/10.18960/seitai.70.1_77>\
**Contents**: 食性解析の手法\
**Usage**:

------------------------------------------------------------------------

**No.04**\
**Title**: 都市生態学序説：「まち」の社会生態プロセスを理解する\
**Author**: 土屋一彬\
**Year**: 2013\
**Link**: <https://doi.org/10.18960/seitai.63.2_179>\
**Contents**: 都市生態系について\
**Usage**: 要旨、はじめに

------------------------------------------------------------------------

**No.06**\
**Title**: Taxon-specific PCR for DNA barcoding arthropod prey in bat faeces\
**Author**: MATT R. K. ZEALE\
**Year**: 2010\
**Link**: <https://doi.org/10.1111/j.1755-0998.2010.02920.x>\
**Contents**: ZBJ-Artプライマー\
**Usage**: 2.3.1

------------------------------------------------------------------------

**No.07**\
**Title**: Identification of Food Plants in the Diet of Japanese Ptarmigan (*Lagopus mutus japonicus*) in the Japan's Northern Japan Alps using DNA Barcoding\
**Author**: Taichi Fujii\
**Year**: 2019\
**Link**: <https://doi.org/10.20798/awhswhs.6.2_13>\
**Contents**: iNEXTパッケージと希釈化曲線\
**Usage**:

------------------------------------------------------------------------

**No.08**\
**Title**: 生態学におけるビッグデータ解析の手法―生物群集解析の基礎理論―\
**Author**: 門脇浩明\
**Year**: 2019\
**Link**: <https://doi.org/10.5956/jriet.48.3_126>\
**Contents**: 希釈法についての説明\
**Usage**:

------------------------------------------------------------------------

**No.09**\
**Title**: iNEXT: an R package for rarefaction and extrapolation of species diversity (Hill numbers)\
**Author**: Anne Chao\
**Year**: 2016\
**Link**: <https://doi.org/10.1111/2041-210X.12613>\
**Contents**: iNEXTパッケージの説明と使用法\
**Usage**: iNEXTパッケージをもちいた解析

------------------------------------------------------------------------

**No.10**\
**Title**: 岡山理科大学生物地球学部生物地球学科旧植物生態学研究室HP「タチキジムシロ　*Potentilla erecta*」\
**Author**:\
**Year**:\
**Link**: <http://www1.ous.ac.jp/garden/hada/plantsdic/angiospermae/dicotyledoneae/choripetalae/rosaceae/potentilla_erecta/potentilla_erecta.htm>\
**Contents**: タチキジムシロ種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.11**\
**Title**: THE IUCN RED LIST OF THREATENED SPIECIES™「Ulmus wallichiana」\
**Author**:\
**Year**:\
**Link**: <https://www.iucnredlist.org/species/30410/9545816>\
**Contents**: Ulmus wallichiana種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.12**\
**Title**: 常緑越冬性コウライシバ (*Zoysia tenuifolia*, 宇都宮大学選抜種) の冬季における葉身部のアミノ酸含有量に関する研究\
**Author**: 赤嶺光\
**Year**: 2001\
**Link**: <https://doi.org/10.11275/turfgrass1972.29.135>\
**Contents**: コウライシバ種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.13**\
**Title**: 日本産ハイゴケ科・ハイゴケ属は現在どのように扱われているのか\
**Author**: 秋山弘之\
**Year**: 2021\
**Link**: <https://doi.org/10.24474/bryologicalresearch.12.6_149>\
**Contents:** ハイゴケ種同定**\
Usage:** 3.3.2種同定

------------------------------------------------------------------------

**No.14**\
**Title**: 広島大学デジタルミュージアム「シラホシコゲチャハエトリ　広島大学東広島キャンパス」\
**Author**:\
**Year**:\
**Link**: <https://www.digital-museum.hiroshima-u.ac.jp/~main/index.php?title=%E3%82%B7%E3%83%A9%E3%83%9B%E3%82%B7%E3%82%B3%E3%82%B2%E3%83%81%E3%83%A3%E3%83%8F%E3%82%A8%E3%83%88%E3%83%AA_%E5%BA%83%E5%B3%B6%E5%A4%A7%E5%AD%A6%E6%9D%B1%E5%BA%83%E5%B3%B6%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%91%E3%82%B9&mobileaction=toggle_view_desktop>\
**Contents**: シラホシコゲチャハエトリ種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.15**\
**Title**: 日本産ゾウムシデータベース\
**Author**: 伊澤和義\
**Year**:\
**Link**: <http://de05.digitalasia.chubu.ac.jp/index.html>\
**Contents**: ゾウムシ種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.16**\
**Title**: 東京大学総合研究博物館　貧毛類標本データベース\
**Author**:\
**Year**:\
**Link**: <https://umdb.um.u-tokyo.ac.jp/DDoubutu/invertebrate/oligochaeta/index.html>\
**Contents**: ミミズ類同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.17**\
**Title**: Biological Information System for Marine Life「Platorchestia humicola」\
**Author:**\
**Year:**\
**Link:** <https://www.godac.jamstec.go.jp/bismal/j/view/9030680>\
**Contents:** オカトビムシ種同定**\
Usage:** 3.3.2種同定

------------------------------------------------------------------------

No.**18**\
**Title**: 日本産ヒメバチ上科(膜翅目)の属への検索表\
**Author**: 渡辺恭平・藤江隼平\
**Year**: 2022\
**Link**:\
**Contents**: ヒメバチ科種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.19**\
**Title**: 農業環境変動研究センター所蔵の田中和夫コレクションオサムシ上科(昆虫綱：コウチュウ目)標本目録\
**Author**: 吉松慎一他\
**Year**: 2018\
**Link**:\
**Contents**: オサムシ科種同定\
**Usage**: 3.3.2種同定

------------------------------------------------------------------------

**No.20**\
**Title**: 都市生態学序説：「まち」の社会生態プロセスを理解する\
**Author**: 土屋一彬他\
**Year**: 2013\
**Link**: <https://doi.org/10.18960/seitai.63.2_179>\
**Contents**: 都市生態系の特徴、都市における生態系サービス\
**Usage**: 1.1都市生態系について

------------------------------------------------------------------------

**No.21**\
**Title**: 市街地の森林の鳥類の分布と多様性：林分構造、景観構造・果実資源量の影響及び種・機能群による違い\
**Author**: 折戸咲子他\
**Year**: 2023\
**Link**: <https://doi.org/10.18960/hozen.2222>\
**Contents**: ムクドリの身体の大きさと好む住処\
**Usage**: 1.2ムクドリについて、考察

------------------------------------------------------------------------

**No.22**\
**Title**: 生物多様性・生態系の保全の科学\
**Author**: 鷲谷いづみ\
**Year**: 2022\
**Link**: <https://doi.org/10.11492/eis.51.1_9>\
**Contents**: 生態系サービス、都市生態系への移行とハビタットの減少\
**Usage**: 1.1都市生態系について

------------------------------------------------------------------------

**No.23**\
**Title**: 人と生態系のダイナミクス 都市生態系の歴史と未来\
**Author**: 飯田晶子他\
**Year**: 2020\
**Link**: <https://www.asakura.co.jp/detail.php?book_code=18543>\
**Contents**: 都市生態系の特徴、都市の生物多様性を守り高めることの意義\
**Usage**: 1.1

------------------------------------------------------------------------

**No.24**\
**Title**: 都市の生物多様性研究は何を目的や対象としてきたか？：国内研究の動向分析\
**Author**: 土屋一彬\
**Year**: 2018\
**Link**: <https://doi.org/10.18960/hozen.23.2_265>\
**Contents**: 考察の参考\
**Usage**:

------------------------------------------------------------------------

**No.25**\
**Title**: 生物多様性保全と都市緑化/可能性と課題\
**Author**: 飯島健太郎\
**Year**: 2016\
**Link**: <https://doi.org/10.11275/turfgrass.44.2_91>\
**Contents**: 都市計画、ムクドリの好む果実、調査対象となる生物、都市緑化空間の例\
**Usage**: 1、考察

------------------------------------------------------------------------

**No.26**\
**Title**: アーバンフォレストリー：多様性の高い都市緑化の創生を目指して\
**Author**: 堀田佳那\
**Year**: 2015\
**Link**: <https://doi.org/10.7211/jjsrt.40.505>\
**Contents**: 均一な植栽の悪影響　考察の参考\
**Usage**:

------------------------------------------------------------------------

**No.27**\
**Title**: 河川が都市の鳥類多様性に与える影響：函館市亀田川の事例\
**Author**: 中川優奈\
**Year**: 2017\
**Link**: <https://doi.org/10.3838/jjo.66.133>\
**Contents**: 河川が持つ役割：山と市街地をつなぐ移動空間となる　考察\
**Usage**:

------------------------------------------------------------------------

**No.28**\
**Title**: 市街地におけるムクドリの集団ねぐらと周辺環境との関係\
**Author**: 與那城千恵\
**Year**: 2020\
**Link**: <https://doi.org/10.5632/jilaonline.13.80>\
**Contents**: 生態系ディスサービスという観点　考察\
**Usage**:

------------------------------------------------------------------------

**No.29**\
**Title**: ムクドリの生態系での役割と街路樹のねぐら問題\
**Author**: 越川重治\
**Year**: 2021\
**Link**: <https://doi.org/10.18938/treeforesthealth.25.2_73>\
**Contents**: ムクドリの生物学的特徴、ムクドリがねぐらとして好む木、ムクドリが食べる餌\
**Usage**: 1.2

------------------------------------------------------------------------

**No.30**\
**Title**: 改訂新版　日本の野生植物4\
**Author**: 大橋広好他\
**Year**: 2017\
**Link**: <https://www.heibonsha.co.jp/book/b202219.html>\
**Contents**: ヤマアジサイ/サワアジサイ\
**Usage**: 3.2.2種同定

------------------------------------------------------------------------

**No.31**\
**Title**: 日本産ミミズ大図鑑\
**Author**: \
**Year**:\
**Link**: <https://japanese-mimizu.jimdofree.com/>\
**Contents**: ミミズの分類\
**Usage**: 3.2.2種同定

------------------------------------------------------------------------

**No.32**\
**Title**:\
**Author**:\
**Year**:\
**Link**:\
**Contents**:\
**Usage**:

------------------------------------------------------------------------

**No.33**\
**Title**:\
**Author**:\
**Year**:\
**Link**:\
**Contents**:\
**Usage**:

------------------------------------------------------------------------

**No.34**\
**Title**:\
**Author**:\
**Year**:\
**Link**:\
**Contents**:\
**Usage**:

------------------------------------------------------------------------

**No.35**\
**Title**:\
**Author**:\
**Year**:\
**Link**:\
**Contents**:\
**Usage**:
